In [8]:
import polars as pl
import os
import glob

In [9]:
DATA_PATH = "../data/raw/idn-news/data_files/*.parquet"

In [11]:
df = pl.scan_parquet(
    DATA_PATH
)

df

In [15]:
print("Jumlah file parquet:", len(files))
print("Ukuran dataset:", round(total_size/(1024**3),2), "GB")

Jumlah file parquet: 441
Ukuran dataset: 1.45 GB

In [16]:
df.select(
    pl.len()
).collect()

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 1149789 │
└─────────┘

In [17]:
df.head(5).collect()

shape: (5, 4)
┌────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ date       ┆ link                            ┆ title                           ┆ text                            │
│ ---        ┆ ---                             ┆ ---                             ┆ ---                             │
│ str        ┆ str                             ┆ str                             ┆ str                             │
╞════════════╪═════════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 2019-05-10 ┆ https://www.cnbcindonesia.com/… ┆ Potret Jemaah Haji Mulai Melak… ┆ Haji tahun ini merupakan tanta… │
│ 2019-08-19 ┆ https://www.cnbcindonesia.com/… ┆ Cek Warga China Mencoba Robot … ┆ Seorang anggota staf mengambil… │
│ 2019-08-26 ┆ https://www.cnbcindonesia.com/… ┆ Ajaib! Tato Elektronik Buatan … ┆ "Di masa depan, apa yang kami … │
│ 2019-10-30 ┆ https://www.cnbcindonesia.com/… ┆ Chairul Tanjung Hadiri BSI GIF… ┆ Menurutnya, karakter anak-anak… │
│ 2022-03-28 ┆ https://www.cnbcindonesia.com/… ┆ 11 Tanda Rumah Anda Sudah Terc… ┆ Jakarta, CNBC Indonesia - Polu… │
└────────────┴─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [18]:
df.select([
    pl.col(col).null_count().alias(col)
    for col in df.collect_schema().names()
]).collect()

shape: (1, 4)
┌──────┬──────┬───────┬──────┐
│ date ┆ link ┆ title ┆ text │
│ ---  ┆ ---  ┆ ---   ┆ ---  │
│ u32  ┆ u32  ┆ u32   ┆ u32  │
╞══════╪══════╪═══════╪══════╡
│ 0    ┆ 0    ┆ 0     ┆ 0    │
└──────┴──────┴───────┴──────┘